import jsPDF from 'jspdf'

// Convert hex to RGB
function hexToRgb(hex) {
    const h = hex.replace('#', '')
    return {
        r: parseInt(h.substring(0, 2), 16),
        g: parseInt(h.substring(2, 4), 16),
        b: parseInt(h.substring(4, 6), 16)
    }
}

// Check if color is light
function isLight(hex) {
    const { r, g, b } = hexToRgb(hex)
    return (r * 299 + g * 587 + b * 114) / 1000 > 128
}

export function generatePDF(brief, visual) {
    const pdf = new jsPDF('p', 'mm', 'a4')
    const W = pdf.internal.pageSize.getWidth()
    const H = pdf.internal.pageSize.getHeight()
    const margin = 16
    const contentW = W - margin * 2
    let y = 0

    // Colors
    const bg = [9, 9, 11]
    const surface = [19, 19, 22]
    const textMain = [228, 228, 231]
    const textMuted = [113, 113, 122]
    const textFaint = [63, 63, 70]
    const border = [35, 35, 41]

    // ============================================
    // HELPERS
    // ============================================
    const setColor = (rgb) => pdf.setTextColor(rgb[0], rgb[1], rgb[2])
    const setFill = (rgb) => pdf.setFillColor(rgb[0], rgb[1], rgb[2])

    const fillPage = () => {
        setFill(bg)
        pdf.rect(0, 0, W, H, 'F')
    }

    const checkPage = (needed) => {
        if (y + needed > H - 20) {
            pdf.addPage()
            fillPage()
            y = margin
        }
    }

    const drawLine = () => {
        setFill(border)
        pdf.rect(margin, y, contentW, 0.3, 'F')
        y += 6
    }

    const writeLabel = (text) => {
        checkPage(10)
        pdf.setFontSize(7)
        pdf.setFont('helvetica', 'bold')
        setColor(textFaint)
        pdf.text(text.toUpperCase(), margin, y)
        y += 5
    }

    const writeTitle = (text, size = 11) => {
        checkPage(12)
        pdf.setFontSize(size)
        pdf.setFont('helvetica', 'bold')
        setColor(textMain)
        const lines = pdf.splitTextToSize(text, contentW)
        pdf.text(lines, margin, y)
        y += lines.length * (size * 0.45) + 2
    }

    const writeBody = (text, size = 8.5) => {
        if (!text) return
        checkPage(10)
        pdf.setFontSize(size)
        pdf.setFont('helvetica', 'normal')
        setColor(textMuted)
        const lines = pdf.splitTextToSize(text, contentW)
        lines.forEach(line => {
            checkPage(5)
            pdf.text(line, margin, y)
            y += 4
        })
        y += 2
    }

    const writeSubtext = (text) => {
        if (!text) return
        checkPage(8)
        pdf.setFontSize(7.5)
        pdf.setFont('helvetica', 'italic')
        setColor(textFaint)
        const lines = pdf.splitTextToSize('→ ' + text, contentW)
        lines.forEach(line => {
            checkPage(4)
            pdf.text(line, margin, y)
            y += 3.5
        })
        y += 2
    }

    // ============================================
    // PAGE 1: COVER
    // ============================================
    fillPage()
    y = 50

    // Logo mark
    setFill(surface)
    pdf.roundedRect(margin, y - 5, 12, 12, 3, 3, 'F')
    pdf.setFontSize(8)
    setColor(textMuted)
    pdf.text('✦', margin + 4, y + 3)

    y += 20

    // Project title
    pdf.setFontSize(22)
    pdf.setFont('helvetica', 'bold')
    setColor(textMain)
    const titleLines = pdf.splitTextToSize(brief.projectTitle || 'Design Brief', contentW)
    pdf.text(titleLines, margin, y)
    y += titleLines.length * 9 + 4

    // Summary
    if (brief.summary) {
        pdf.setFontSize(10)
        pdf.setFont('helvetica', 'normal')
        setColor(textMuted)
        const sumLines = pdf.splitTextToSize(brief.summary, contentW * 0.8)
        pdf.text(sumLines, margin, y)
        y += sumLines.length * 5 + 8
    }

    // Meta info
    drawLine()
    pdf.setFontSize(7)
    pdf.setFont('helvetica', 'normal')
    setColor(textFaint)
    pdf.text(`Generated by Aurora AI Design Partner`, margin, y)
    y += 4
    pdf.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), margin, y)
    y += 4
    pdf.text(`Tone: ${brief.toneAndPersonality?.primary || ''} / ${brief.toneAndPersonality?.secondary || ''}`, margin, y)

    // ============================================
    // PAGE 2: COLOR PALETTE
    // ============================================
    pdf.addPage()
    fillPage()
    y = margin

    writeLabel('Color Palette')
    y += 2

    // Color swatches - big blocks
    if (brief.colorPalette?.length > 0) {
        const swatchW = (contentW - (brief.colorPalette.length - 1) * 2) / brief.colorPalette.length
        const swatchH = 22

        brief.colorPalette.forEach((c, i) => {
            const x = margin + i * (swatchW + 2)
            const rgb = hexToRgb(c.hex)
            pdf.setFillColor(rgb.r, rgb.g, rgb.b)
            pdf.roundedRect(x, y, swatchW, swatchH, 2, 2, 'F')

            // Color name on swatch
            pdf.setFontSize(6)
            const txtColor = isLight(c.hex) ? [0, 0, 0] : [255, 255, 255]
            pdf.setTextColor(txtColor[0], txtColor[1], txtColor[2])
            pdf.setFont('helvetica', 'bold')
            pdf.text(c.name, x + 3, y + 6)
            pdf.setFont('helvetica', 'normal')
            pdf.text(c.hex, x + 3, y + 10)
        })

        y += swatchH + 8

        // Detailed color explanations
        brief.colorPalette.forEach(c => {
            checkPage(22)

            // Mini swatch
            const rgb = hexToRgb(c.hex)
            pdf.setFillColor(rgb.r, rgb.g, rgb.b)
            pdf.roundedRect(margin, y - 3, 6, 6, 1, 1, 'F')

            // Name and hex
            pdf.setFontSize(9)
            pdf.setFont('helvetica', 'bold')
            setColor(textMain)
            pdf.text(`${c.name}`, margin + 10, y)

            pdf.setFont('helvetica', 'normal')
            pdf.setFontSize(8)
            setColor(textFaint)
            pdf.text(c.hex, margin + 10 + pdf.getTextWidth(c.name + '  '), y)
            y += 4

            // Usage
            if (c.usage) {
                pdf.setFontSize(7.5)
                setColor(textMuted)
                pdf.text(`Usage: ${c.usage}`, margin + 10, y)
                y += 4
            }

            // Psychology
            if (c.psychology) {
                pdf.setFontSize(7.5)
                setColor(textFaint)
                const psychLines = pdf.splitTextToSize(`Why: ${c.psychology}`, contentW - 12)
                psychLines.forEach(line => {
                    checkPage(4)
                    pdf.text(line, margin + 10, y)
                    y += 3.5
                })
            }
            y += 4
        })
    }

    // ============================================
    // PAGE 3: AUDIENCE & TONE
    // ============================================
    pdf.addPage()
    fillPage()
    y = margin

    // Audience
    if (brief.targetAudience) {
        writeLabel('Target Audience')
        writeTitle(brief.targetAudience.primary, 11)
        writeBody(`Age: ${brief.targetAudience.ageRange}`)
        writeBody(brief.targetAudience.psychographics)
        if (brief.targetAudience.painPoints) {
            y += 2
            writeLabel('Pain Points')
            writeBody(brief.targetAudience.painPoints)
        }
        writeSubtext(brief.targetAudience.designImplication)
        y += 4
        drawLine()
    }

    // Tone
    if (brief.toneAndPersonality) {
        writeLabel('Tone & Personality')
        writeTitle(`${brief.toneAndPersonality.primary} / ${brief.toneAndPersonality.secondary}`, 10)
        writeBody(`Brand voice: "${brief.toneAndPersonality.brandVoice}"`)
        if (brief.toneAndPersonality.emotionalGoal) {
            writeLabel('Emotional Goal')
            writeBody(brief.toneAndPersonality.emotionalGoal)
        }
        writeSubtext(brief.toneAndPersonality.reasoning)
        y += 4
        drawLine()
    }

    // Typography
    if (brief.typography) {
        writeLabel('Typography')
        writeTitle(`${brief.typography.headingFont} + ${brief.typography.bodyFont}`, 10)
        writeBody(brief.typography.style)
        if (brief.typography.scale) writeBody(`Type scale: ${brief.typography.scale}`)
        writeSubtext(brief.typography.reasoning)
    }

    // ============================================
    // PAGE 4: LAYOUT & REASONING
    // ============================================
    pdf.addPage()
    fillPage()
    y = margin

    // Layout
    if (brief.layoutStructure) {
        writeLabel('Layout Structure')
        brief.layoutStructure.sections?.forEach((s, i) => {
            checkPage(6)
            pdf.setFontSize(8.5)
            pdf.setFont('helvetica', 'normal')
            setColor(textMuted)
            pdf.text(`${i + 1}.  ${s}`, margin, y)
            y += 5
        })
        y += 3
        writeLabel('Hero Approach')
        writeBody(brief.layoutStructure.heroStyle)
        writeLabel('CTA Strategy')
        writeBody(brief.layoutStructure.ctaStrategy)
        if (brief.layoutStructure.userFlow) {
            writeLabel('User Flow')
            writeBody(brief.layoutStructure.userFlow)
        }
        writeSubtext(brief.layoutStructure.reasoning)
        y += 4
        drawLine()
    }

    // Strategic Reasoning
    if (brief.uxReasoning) {
        writeLabel('Strategic Design Reasoning')
        y += 1

        // Highlight box
        checkPage(20)
        setFill(surface)
        const reasonLines = pdf.splitTextToSize(brief.uxReasoning, contentW - 12)
        const boxH = reasonLines.length * 4 + 10
        pdf.roundedRect(margin, y - 2, contentW, boxH, 2, 2, 'F')

        pdf.setFontSize(8.5)
        pdf.setFont('helvetica', 'normal')
        setColor([161, 161, 170])
        reasonLines.forEach(line => {
            pdf.text(line, margin + 6, y + 4)
            y += 4
        })
        y += 10
    }

    // Accessibility
    if (brief.accessibilityNotes) {
        drawLine()
        writeLabel('Accessibility Notes')
        writeBody(brief.accessibilityNotes)
    }

    // Competitive
    if (brief.competitiveInsight) {
        y += 2
        writeLabel('Competitive Differentiator')
        writeBody(brief.competitiveInsight)
    }

    // ============================================
    // PAGE 5: VISUAL CONCEPT (if available)
    // ============================================
    if (visual?.description) {
        pdf.addPage()
        fillPage()
        y = margin

        writeLabel('Visual Concept')
        y += 4

        // Color strip representation
        if (visual.colors?.length > 0) {
            const stripW = contentW / visual.colors.length
            visual.colors.forEach((c, i) => {
                const rgb = hexToRgb(c.hex)
                pdf.setFillColor(rgb.r, rgb.g, rgb.b)
                pdf.rect(margin + i * stripW, y, stripW, 4, 'F')
            })
            y += 10
        }

        // Visual description
        writeLabel('AI Visual Description')
        y += 1

        setFill(surface)
        const descLines = pdf.splitTextToSize(visual.description, contentW - 12)
        const descH = descLines.length * 4 + 10
        pdf.roundedRect(margin, y - 2, contentW, descH, 2, 2, 'F')

        pdf.setFontSize(8.5)
        setColor(textMuted)
        descLines.forEach(line => {
            pdf.text(line, margin + 6, y + 4)
            y += 4
        })
        y += 12

        // Image generation prompt
        if (visual.prompt) {
            writeLabel('Generation Prompt')
            pdf.setFontSize(7)
            pdf.setFont('helvetica', 'italic')
            setColor(textFaint)
            const promptLines = pdf.splitTextToSize(visual.prompt, contentW)
            promptLines.forEach(line => {
                checkPage(4)
                pdf.text(line, margin, y)
                y += 3.5
            })
        }
    }

    // ============================================
    // DESIGN TOKENS PAGE
    // ============================================
    if (brief.designTokens) {
        pdf.addPage()
        fillPage()
        y = margin

        writeLabel('Design Tokens')
        y += 4

        const tokens = [
            { key: 'Border Radius', val: brief.designTokens.borderRadius },
            { key: 'Base Spacing', val: brief.designTokens.spacing },
            { key: 'Shadow Style', val: brief.designTokens.shadowStyle },
            { key: 'Animation', val: brief.designTokens.animationStyle }
        ]

        tokens.forEach(t => {
            if (!t.val) return
            checkPage(8)
            pdf.setFontSize(8)
            pdf.setFont('helvetica', 'bold')
            setColor(textMuted)
            pdf.text(t.key, margin, y)
            pdf.setFont('helvetica', 'normal')
            setColor(textMain)
            pdf.text(String(t.val), margin + 35, y)
            y += 6
        })

        y += 6
        writeLabel('Mood Keywords')
        y += 2

        if (brief.moodKeywords?.length > 0) {
            pdf.setFontSize(8)
            pdf.setFont('helvetica', 'normal')
            setColor(textMuted)
            pdf.text(brief.moodKeywords.map(k => `#${k}`).join('  '), margin, y)
        }
    }

    // ============================================
    // FOOTER on every page
    // ============================================
    const totalPages = pdf.internal.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i)
        pdf.setFontSize(6)
        pdf.setFont('helvetica', 'normal')
        pdf.setTextColor(39, 39, 42)
        pdf.text(`Aurora — AI Design Partner`, margin, H - 8)
        pdf.text(`${i} / ${totalPages}`, W - margin - 10, H - 8)
    }

    // Save
    const filename = (brief.projectTitle || 'aurora-brief').toLowerCase().replace(/[^a-z0-9]+/g, '-')
    pdf.save(`${filename}.pdf`)
}