import { useState } from 'react'
import { Copy, Check } from 'lucide-react'

function ExportCode({ brief, showToast }) {
    const [tab, setTab] = useState('css')
    const [copied, setCopied] = useState(false)

    if (!brief) return null

    const colors = brief.colorPalette || []
    const tokens = brief.designTokens || {}

    // Generate CSS Variables
    const cssCode = `:root {
  /* Colors — Generated by Aurora */
${colors.map(c => `  --color-${c.name.toLowerCase()}: ${c.hex};`).join('\n')}

  /* Typography */
  --font-heading: '${brief.typography?.headingFont || 'Inter'}', sans-serif;
  --font-body: '${brief.typography?.bodyFont || 'Inter'}', sans-serif;

  /* Spacing & Shape */
  --radius: ${tokens.borderRadius || '8px'};
  --spacing: ${tokens.spacing || '16px'};
}

/* Base Styles */
body {
  font-family: var(--font-body);
  background-color: var(--color-background);
  color: var(--color-text);
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  color: var(--color-text);
}

.btn-primary {
  background-color: var(--color-primary);
  color: var(--color-background);
  padding: calc(var(--spacing) * 0.5) var(--spacing);
  border-radius: var(--radius);
  border: none;
  font-family: var(--font-body);
  font-weight: 600;
  cursor: pointer;
  transition: opacity 0.2s ease;
}

.btn-primary:hover {
  opacity: 0.9;
}

.card {
  background-color: var(--color-secondary);
  border-radius: var(--radius);
  padding: var(--spacing);
  border: 1px solid color-mix(in srgb, var(--color-text) 10%, transparent);
}`

    // Generate Tailwind Config
    const tailwindCode = `// tailwind.config.js — Generated by Aurora

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
${colors.map(c => `        '${c.name.toLowerCase()}': '${c.hex}',`).join('\n')}
      },
      fontFamily: {
        heading: ['${brief.typography?.headingFont || 'Inter'}', 'sans-serif'],
        body: ['${brief.typography?.bodyFont || 'Inter'}', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '${tokens.borderRadius || '8px'}',
      },
      spacing: {
        'base': '${tokens.spacing || '16px'}',
      }
    },
  },
  plugins: [],
}`

    // Generate SCSS Variables
    const scssCode = `// _variables.scss — Generated by Aurora

// Colors
${colors.map(c => `$color-${c.name.toLowerCase()}: ${c.hex};`).join('\n')}

// Typography
$font-heading: '${brief.typography?.headingFont || 'Inter'}', sans-serif;
$font-body: '${brief.typography?.bodyFont || 'Inter'}', sans-serif;

// Tokens
$radius: ${tokens.borderRadius || '8px'};
$spacing: ${tokens.spacing || '16px'};
$shadow-style: ${tokens.shadowStyle || 'subtle'};

// Mixins
@mixin card {
  background-color: $color-secondary;
  border-radius: $radius;
  padding: $spacing;
  border: 1px solid rgba($color-text, 0.1);
}

@mixin button-primary {
  background-color: $color-primary;
  color: $color-background;
  padding: ($spacing / 2) $spacing;
  border-radius: $radius;
  font-family: $font-body;
  font-weight: 600;
  border: none;
  cursor: pointer;
  &:hover { opacity: 0.9; }
}`

    // JSON Tokens
    const jsonCode = JSON.stringify({
        colors: Object.fromEntries(colors.map(c => [c.name.toLowerCase(), { value: c.hex, usage: c.usage }])),
        typography: {
            heading: { fontFamily: brief.typography?.headingFont, weight: '600-700' },
            body: { fontFamily: brief.typography?.bodyFont, weight: '400-500' }
        },
        tokens: {
            borderRadius: tokens.borderRadius || '8px',
            spacing: tokens.spacing || '16px',
            shadowStyle: tokens.shadowStyle || 'subtle',
            animationStyle: tokens.animationStyle || 'smooth'
        },
        metadata: {
            project: brief.projectTitle,
            generatedBy: 'Aurora AI Design Partner',
            tone: [brief.toneAndPersonality?.primary, brief.toneAndPersonality?.secondary]
        }
    }, null, 2)

    const tabs = [
        { id: 'css', label: 'CSS' },
        { id: 'tailwind', label: 'Tailwind' },
        { id: 'scss', label: 'SCSS' },
        { id: 'json', label: 'Tokens' }
    ]

    const codeMap = { css: cssCode, tailwind: tailwindCode, scss: scssCode, json: jsonCode }

    const copyCode = () => {
        navigator.clipboard.writeText(codeMap[tab])
        setCopied(true)
        showToast(`${tab.toUpperCase()} copied to clipboard`)
        setTimeout(() => setCopied(false), 1500)
    }

    const downloadCode = () => {
        const ext = { css: 'css', tailwind: 'js', scss: 'scss', json: 'json' }
        const filename = { css: 'aurora-variables.css', tailwind: 'tailwind.config.js', scss: '_variables.scss', json: 'design-tokens.json' }
        const blob = new Blob([codeMap[tab]], { type: 'text/plain' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = filename[tab]
        a.click()
        URL.revokeObjectURL(url)
        showToast(`${filename[tab]} downloaded`)
    }

    return (
        <div className="mt-6 enter">
            <div className="overflow-hidden" style={{ background: '#131316', border: '1px solid #232329', borderRadius: '20px' }}>
                {/* Tab bar */}
                <div className="flex items-center justify-between px-4 py-2" style={{ borderBottom: '1px solid #232329' }}>
                    <div className="flex gap-1">
                        {tabs.map(t => (
                            <button key={t.id} onClick={() => setTab(t.id)}
                                className="px-3 py-1.5 rounded-lg text-[11px] font-medium transition-all"
                                style={{
                                    backgroundColor: tab === t.id ? '#1a1a1f' : 'transparent',
                                    color: tab === t.id ? '#e4e4e7' : '#3f3f46',
                                    border: tab === t.id ? '1px solid #2e2e36' : '1px solid transparent'
                                }}>
                                {t.label}
                            </button>
                        ))}
                    </div>
                    <div className="flex items-center gap-1.5">
                        <button onClick={copyCode} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] transition-all"
                            style={{ color: '#71717a', border: '1px solid #232329' }}
                            onMouseEnter={e => { e.currentTarget.style.borderColor = '#2e2e36'; e.currentTarget.style.color = '#e4e4e7' }}
                            onMouseLeave={e => { e.currentTarget.style.borderColor = '#232329'; e.currentTarget.style.color = '#71717a' }}>
                            {copied ? <Check size={11} /> : <Copy size={11} />}
                            {copied ? 'Copied' : 'Copy'}
                        </button>
                        <button onClick={downloadCode} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] transition-all"
                            style={{ backgroundColor: '#e4e4e7', color: '#09090b', fontWeight: 600 }}>
                            Download
                        </button>
                    </div>
                </div>

                {/* Code area */}
                <div className="p-5 overflow-x-auto" style={{ maxHeight: '400px', overflowY: 'auto' }}>
                    <pre className="text-[12px] leading-relaxed font-mono whitespace-pre" style={{ color: '#a1a1aa' }}>
                        {codeMap[tab]}
                    </pre>
                </div>
            </div>
        </div>
    )
}

export default ExportCode